# Generated by Django 5.2 on 2025-07-14 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_compensacao', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('microrregiao', models.CharField(blank=True, max_length=255)),
                ('mesorregiao', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
                ('regiao_nome', models.CharField(max_length=100)),
                ('regiao_sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1)),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('usuarios', models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_assinatura', models.DateField()),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('quitado', 'Quitado'), ('parcelado', 'Parcelado'), ('renegociado', 'Renegociado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('desativada', 'Desativada'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1)),
                ('documento', models.CharField(max_length=18)),
                ('ultima_remessa', models.DateField(blank=True, null=True)),
                ('protesto_automatico', models.CharField(choices=[('nao', 'Não protestar'), ('sim', 'Protestar automaticamente')], default='nao', max_length=10)),
                ('dias_protesto', models.PositiveIntegerField(default=0)),
                ('multa_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('juros_dia_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('titulo', models.CharField(choices=[('cobranca_simples', 'Cobrança Simples'), ('cobranca_vinculada', 'Cobrança Vinculada'), ('descontada', 'Descontada'), ('cobranca_direta', 'Cobrança Direta'), ('outros', 'Outros')], default='cobranca_simples', max_length=30)),
                ('cedente', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=10)),
                ('digito_agencia', models.CharField(max_length=2)),
                ('conta', models.CharField(max_length=20)),
                ('digito_conta', models.CharField(max_length=2)),
                ('prefixo', models.PositiveSmallIntegerField()),
                ('carteira', models.CharField(max_length=10)),
                ('modalidade', models.CharField(max_length=10)),
                ('especie_documento', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='core.banco')),
                ('conta_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='core.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.estado'),
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('boleto', 'Boleto')], max_length=20)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=10)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela_afetada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField()),
                ('acao', models.CharField(choices=[('INSERT', 'Inserção'), ('UPDATE', 'Atualização'), ('DELETE', 'Remoção')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
