# Generated by Django 5.2 on 2025-07-25 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contrato_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento'),
        ),
    ]
