# Generated by Django 5.2 on 2025-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contrato_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='codigo_inter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Banco Inter'),
        ),
    ]
